#https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
#We will follow descending order
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-class-ds
value: 20000000
globalDefault: false
description: "Daemonsets"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-class-ingress
value: 80999
globalDefault: false
description: "ingress"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-class-clusterautoscaler-metricsserver
value: 70999
globalDefault: false
description: "cluster-autoscaler, metrics server"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-class-mw-pods
value: 60999
globalDefault: false
description: "mw pods"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-class-monitoring
value: 50999
globalDefault: false
description: "monitoring"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-class-global-default
value: 40999
globalDefault: true
description: "global-default"